name: pr-opened
on:
  # Run for PRs to main
  pull_request:
    branches:
    - main
    types: [ opened, synchronized ]


jobs:
  # Detect any changes to Docker files
  docker-check:
    runs-on: ubuntu-latest
    uses: ./.github/workflows/docker-check.yml

  # Build the Docker image if Docker files changed
  docker-build:
    needs: [ docker-check ]
    if : ${{ needs.docker-check.outputs.docker_changed == 'true' }}
    uses: ./.github/workflows/docker-build.yml
    secrets: inherit

  # Run the main tests
  test:
    needs: [ docker-build ]
    # Allow skipping docker-build if no Docker files changed
    if: always() && !failure() && !cancelled()
    runs-on: ubuntu-24.04

    uses: ./.github/workflows/pipeline.yml
    secrets: inherit
    with:
      container_tag: pr-${{ github.event.pull_request.number }}
