name: pr-opened
on:
  # Run for PRs to main
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize]

jobs:
  # Detect any changes to Docker files
  docker-check:
    uses: ./.github/workflows/docker-check.yml

  # Build the Docker image if Docker files changed
  docker-build:
    needs: [docker-check]
    if: ${{ needs.docker-check.outputs.docker_changed == 'true' }}
    uses: ./.github/workflows/docker-build.yml

  # Run the main tests
  test:
    needs: [docker-build]
    # Allow skipping docker-build if no Docker files changed
    if: always() && !failure() && !cancelled()
    uses: ./.github/workflows/pipeline.yml
    with:
      container_tag: pr-${{ github.event.pull_request.number }}