name: docker-promote

on:
  workflow_call:
    inputs:
      pr_number:
        required: true
        type: string

env:
  REGISTRY_IMAGE: fcsproj/fastcalosim

jobs:
  promote:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ alma9, ubuntu24 ]
    permissions:
      packages: write
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Promote PR image to latest
      run: |
        echo "Promoting PR image to latest for ${{ matrix.os }}"
        PR_TAG="pr-${{ github.event.pull_request.number }}"

        docker buildx imagetools create \
          --tag ${{ env.REGISTRY_IMAGE }}-${{ matrix.os }}:latest \
          ${{ env.REGISTRY_IMAGE }}-${{ matrix.os }}:$PR_TAG

        echo "Image promoted successfully"
        docker buildx imagetools inspect ${{ env.REGISTRY_IMAGE }}-${{ matrix.os }}:latest
